return {
    PassGifts = {
        [1628441770] = 3477243681,
        [1639564273] = 3485587150,
        [1640776898] = 3491607849,
        [1823047083] = 3491607849,
        [1826698184] = 3491607849,
        [1883183171] = 3605582282,
        [1648071738] = 3487189664,
        [1651738174] = 3499391893,
        [1831083023] = 3589736128,
        [1850117073] = 3599668112,
        [1850830962] = 3599668307
    },
    InventoryUpgradePrices = {
        [700] = 750,
        [800] = 2300,
        [900] = 3500,
        [1000] = 5000
    },
    Tasks = {
        U520 = {
            Heading = "Upgrade 5 NFTs with a chance of less than 20%",
            Reward = 150,
            Goal = 5,
            Trigger = "Upgrade_<20",
            Icon = 124295328030749,
            Duration = "Daily",
            XPReward = 1100
        },
        OC500 = {
            Heading = "Open 500 cases",
            Reward = 150,
            Goal = 500,
            Trigger = "Case",
            Icon = 118050483437552,
            Duration = "Daily",
            XPReward = 1100
        },
        OC100 = {
            Heading = "Open 100 cases",
            Reward = 50,
            Goal = 100,
            Trigger = "Case",
            Icon = 118050483437552,
            Duration = "Daily",
            XPReward = 700
        },
        T20 = {
            Heading = "Spend 20 minutes in the game",
            Reward = 300,
            Goal = 1200,
            Trigger = "Playtime",
            Icon = 129675264104051,
            Duration = "Daily",
            XPReward = 700
        },
        T30 = {
            Heading = "Spend 30 minutes in the game",
            Reward = 500,
            Goal = 1800,
            Trigger = "Playtime",
            Icon = 129675264104051,
            Duration = "Daily",
            XPReward = 700
        },
        F15N = {
            Heading = "Fuse 15 NFTs",
            Reward = 600,
            Goal = 15,
            Trigger = "Fuse_NFTs",
            Icon = 122387777939578,
            Duration = "Daily",
            XPReward = 800
        },
        G10N500 = {
            Heading = "Get 10 NFTs worth more than 500,000",
            Reward = 500,
            Goal = 10,
            Trigger = "Index",
            Icon = 100278495100224,
            Duration = "Weekly",
            XPReward = 4000
        },
        G10N1000 = {
            Heading = "Get 10 NFTs worth more than 1,000,000",
            Reward = 750,
            Goal = 10,
            Trigger = "Index",
            Icon = 100278495100224,
            Duration = "Weekly",
            XPReward = 4000
        },
        U1000F = {
            Heading = "Fail the upgrade 1,000 times",
            Reward = 1000,
            Goal = 1000,
            Trigger = "Upgrade_Fail",
            Icon = 124295328030749,
            Duration = "Weekly",
            XPReward = 6000
        },
        OC5000 = {
            Heading = "Open 5,000 cases",
            Reward = 750,
            Goal = 5000,
            Trigger = "Case",
            Icon = 118050483437552,
            Duration = "Weekly",
            XPReward = 6000
        },
        T200 = {
            Heading = "Spend 200 minutes in the game",
            Reward = 1000,
            Goal = 12000,
            Trigger = "Playtime",
            Icon = 129675264104051,
            Duration = "Weekly",
            XPReward = 4000
        },
        T300 = {
            Heading = "Spend 300 minutes in the game",
            Reward = 1500,
            Goal = 18000,
            Trigger = "Playtime",
            Icon = 129675264104051,
            Duration = "Weekly",
            XPReward = 6000
        },
        F3B = {
            Heading = "Fuse 3 NFTs with a black backdrop",
            Reward = 1500,
            Goal = 3,
            Trigger = "Fuse_Black",
            Icon = 122387777939578,
            Duration = "Weekly",
            XPReward = 6000
        },
        U2515 = {
            Heading = "Upgrade 25 NFTs with a chance of less than 15%",
            Reward = 1500,
            Goal = 25,
            Trigger = "Upgrade_<15",
            Icon = 124295328030749,
            Duration = "Weekly",
            XPReward = 6000
        }
    },
    Backdrops = {
        ["Midnight Blue"] = Color3.new(0.27451, 0.321569, 0.423529),
        ["Silver Blue"] = Color3.new(0.431373, 0.556863, 0.639216),
        ["Desert Sand"] = Color3.new(0.588235, 0.529412, 0.415686),
        Persimmon = Color3.new(0.827451, 0.517647, 0.356863),
        Turquoise = Color3.new(0.294118, 0.654902, 0.635294),
        Cappuccino = Color3.new(0.584314, 0.470588, 0.407843),
        ["Pacific Green"] = Color3.new(0.333333, 0.698039, 0.552941),
        Malachite = Color3.new(0.415686, 0.647059, 0.32549),
        Amber = Color3.new(0.776471, 0.603922, 0.211765),
        Copper = Color3.new(0.721569, 0.462745, 0.266667),
        ["Dark Lilac"] = Color3.new(0.627451, 0.411765, 0.564706),
        Emerald = Color3.new(0.360784, 0.705882, 0.478431),
        Aquamarine = Color3.new(0.321569, 0.682353, 0.639216),
        Black = Color3.new(0.109804, 0.117647, 0.113725),
        ["Electric Indigo"] = Color3.new(0.517647, 0.443137, 0.898039),
        Fandango = Color3.new(0.768627, 0.439216, 0.631373),
        ["Pure Gold"] = Color3.new(0.694118, 0.580392, 0.215686),
        Strawberry = Color3.new(0.792157, 0.45098, 0.392157),
        Chestnut = Color3.new(0.662745, 0.345098, 0.262745),
        Lemongrass = Color3.new(0.517647, 0.65098, 0.309804),
        ["Pine Green"] = Color3.new(0.329412, 0.564706, 0.454902),
        ["Sky Blue"] = Color3.new(0.32549, 0.627451, 0.760784),
        ["French Blue"] = Color3.new(0.286275, 0.529412, 0.690196),
        ["Ivory White"] = Color3.new(0.678431, 0.666667, 0.639216),
        ["Roman Silver"] = Color3.new(0.564706, 0.580392, 0.627451),
        ["Satin Gold"] = Color3.new(0.654902, 0.537255, 0.25098),
        ["Shamrock Green"] = Color3.new(0.427451, 0.643137, 0.32549),
        ["Mystic Pearl"] = Color3.new(0.752941, 0.443137, 0.423529),
        ["Neon Blue"] = Color3.new(0.427451, 0.490196, 0.933333),
        ["Pacific Cyan"] = Color3.new(0.294118, 0.666667, 0.682353),
        Lavender = Color3.new(0.631373, 0.447059, 0.815686),
        ["Mint Green"] = Color3.new(0.380392, 0.709804, 0.427451),
        Pistachio = Color3.new(0.470588, 0.6, 0.384314),
        Cyberpunk = Color3.new(0.517647, 0.466667, 0.882353),
        ["English Violet"] = Color3.new(0.611765, 0.435294, 0.654902),
        ["Battleship Grey"] = Color3.new(0.47451, 0.478431, 0.454902),
        ["Hunter Green"] = Color3.new(0.423529, 0.603922, 0.407843),
        Raspberry = Color3.new(0.811765, 0.427451, 0.505882),
        Burgundy = Color3.new(0.545098, 0.309804, 0.34902),
        ["Carrot Juice"] = Color3.new(0.815686, 0.521569, 0.356863),
        Orange = Color3.new(0.788235, 0.517647, 0.247059),
        ["Electric Purple"] = Color3.new(0.690196, 0.407843, 0.796078),
        ["Steel Grey"] = Color3.new(0.494118, 0.54902, 0.592157),
        ["Jade Green"] = Color3.new(0.278431, 0.686275, 0.541176),
        Purple = Color3.new(0.607843, 0.345098, 0.607843),
        ["Cobalt Blue"] = Color3.new(0.341176, 0.454902, 0.760784),
        ["Coral Red"] = Color3.new(0.807843, 0.466667, 0.360784),
        Grape = Color3.new(0.541176, 0.380392, 0.690196),
        ["Light Olive"] = Color3.new(0.65098, 0.592157, 0.329412),
        Moonstone = Color3.new(0.415686, 0.607843, 0.635294),
        ["Indigo Dye"] = Color3.new(0.286275, 0.427451, 0.521569),
        ["Khaki Green"] = Color3.new(0.556863, 0.6, 0.380392),
        ["Navy Blue"] = Color3.new(0.384314, 0.533333, 0.823529),
        Sapphire = Color3.new(0.321569, 0.556863, 0.768627),
        ["Azure Blue"] = Color3.new(0.305882, 0.619608, 0.72549),
        Rosewood = Color3.new(0.615686, 0.380392, 0.388235),
        Chocolate = Color3.new(0.552941, 0.352941, 0.286275),
        ["Onyx Black"] = Color3.new(0.243137, 0.258824, 0.270588),
        Caramel = Color3.new(0.768627, 0.52549, 0.184314),
        Platinum = Color3.new(0.619608, 0.607843, 0.580392)
    },
    Patterns = {
        Trophy = 117479871889152,
        ["Celtic Wolf"] = 114188406353483,
        Knight = 82633658007831,
        ["Money Bag"] = 129796307532758,
        Kitsune = 117067198951199,
        Phoenix = 87734118842337,
        Pyramid = 76756089746419,
        Gem = 115293003693851,
        ["Coin Purse"] = 115159233492922,
        Diamond = 110345687858105,
        ["Hand of God"] = 101142450372851,
        ["Royal Crown"] = 78114204561396,
        Shield = 133954101100727,
        ["Spirit Impala"] = 96395329942937,
        Cash = 115034342341089,
        ["Ink Pen"] = 104512102979586,
        ["Lion Head"] = 88222831633682,
        ["Moon Cross"] = 121025320107726,
        Sparks = 107481061057727,
        ["Flower Cross"] = 89155514975611,
        ["Moon Eagle"] = 78457965583264,
        Car = 96973634449292,
        Cobra = 123788941823791,
        Dice = 77148608742178,
        Moon = 91869286875981,
        Wreath = 82870271032181,
        Baphomet = 110662661355149,
        Crown = 120411713952216,
        Pearl = 126444844462465,
        Star = 123580826852107,
        ["The Eye"] = 71909737110496,
        Coin = 83906505399852,
        Chest = 102902190159312,
        ["Bubble Tea"] = 73837135556655,
        ["Coffee Bean"] = 113879361409434,
        Melon = 122649129291520,
        ["Oxen of Fire"] = 118269183124770,
        Sakura = 100285201336069,
        Sauron = 93844620871461,
        Axe = 132777502315479,
        ["Musical Note"] = 84890822768848,
        ["Shark Knife"] = 87859219845249,
        Illuminati = 135274622332330,
        ["Blood Drop"] = 72617488004592,
        Skull = 96871306751245,
        ["Sun Mountain"] = 74322440781800,
        Vortex = 106529198997576,
        ["Gift Box"] = 87252769454998,
        ["Spider Web"] = 112620453732886,
        Fire = 75411239678524
    },
    PaidCases = {
        Pepe10 = {
            3477217543,
            3477217722,
            3477218219,
            3477218451,
            3477218699,
            3477218914,
            3477219204,
            3477219478,
            3477221963,
            3477222195
        },
        Starter = {
            3477211095,
            3477211298,
            3477211513,
            3477211704,
            3477211865,
            3477212092,
            3477212285,
            3477212531,
            3477212779,
            3477212961
        },
        Premium = {
            3477215092,
            3477215291,
            3477215484,
            3477215703,
            3477215865,
            3477216149,
            3477216343,
            3477216564,
            3477216876,
            3477217094
        },
        ["All In"] = {
            3477239344,
            3477239620,
            3477239781,
            3477239981,
            3477240151,
            3477240287,
            3477240480,
            3477240587,
            3477240735,
            3477240924
        },
        ["Last Chance"] = {
            3446816531,
            3446816937,
            3446817215,
            3446817447,
            3446817676,
            3446817906,
            3446818132,
            3446818417,
            3446818866,
            3446819099
        }
    },
    Gifts = {
        Gift = {
            Price = 25,
            Image = 103940759769216
        },
        Rose = {
            Price = 25,
            Image = 103652071849313
        },
        Rocket = {
            Price = 50,
            Image = 138751193627843
        },
        Flowers = {
            Price = 50,
            Image = 121729934336637
        },
        Diamond = {
            Price = 100,
            Image = 86071898628290
        },
        ["Lol Pop"] = {
            Price = 325,
            Image = 119786618365821
        },
        ["Snoop Dogg"] = {
            Price = 425,
            Image = 74491569017648
        },
        ["Jester Hat"] = {
            Price = 500,
            Image = 91398591447906
        },
        Ring = {
            Price = 100,
            Image = 115269956284457
        },
        ["Snake Box"] = {
            Price = 325,
            Image = 117868405841811
        },
        ["Xmax Stocking"] = {
            Price = 350,
            Image = 106078941431777
        },
        ["Gigner Cookie"] = {
            Price = 450,
            Image = 137639922758276
        },
        ["Pet Snake"] = {
            Price = 450,
            Image = 123038440918829
        },
        ["Hex Pox"] = {
            Price = 700,
            Image = 136985175728337
        },
        ["Sakura Flower"] = {
            Price = 1075,
            Image = 89896517362001
        },
        ["Hanging Star"] = {
            Price = 1225,
            Image = 139473883116321
        },
        ["Eternal Rose"] = {
            Price = 3325,
            Image = 85497541474773
        },
        ["Kissed Frog"] = {
            Price = 8625,
            Image = 115450471652876
        },
        ["Perfume Bottle"] = {
            Price = 17350,
            Image = 137505232397334
        },
        ["Hypno Lollipop"] = {
            Price = 475,
            Image = 93924889050705
        },
        ["Star Notepad"] = {
            Price = 600,
            Image = 76738560834486
        },
        ["Light Sword"] = {
            Price = 725,
            Image = 91543876923563
        },
        ["Jolly Chimp"] = {
            Price = 900,
            Image = 99572429300042
        },
        ["Valentine Box"] = {
            Price = 1175,
            Image = 102094416171283
        },
        ["Trapped Heart"] = {
            Price = 2075,
            Image = 121585017318097
        },
        ["Voodoo Doll"] = {
            Price = 3725,
            Image = 76855748485334
        },
        ["Scared Cat"] = {
            Price = 10500,
            Image = 78079063832035
        },
        ["Loot Bag"] = {
            Price = 19375,
            Image = 91248581958205
        },
        ["Mini Oscar"] = {
            Price = 30250,
            Image = 139993313650107
        },
        ["Party Sparkler"] = {
            Price = 500,
            Image = 129296544741520
        },
        ["Spy Agaric"] = {
            Price = 725,
            Image = 89709364600474
        },
        ["Berry Box"] = {
            Price = 875,
            Image = 99761385322275
        },
        ["Record Player"] = {
            Price = 2200,
            Image = 103485916724328
        },
        ["Cupid Charm"] = {
            Price = 2875,
            Image = 77793207752917
        },
        ["Toy Bear"] = {
            Price = 4250,
            Image = 72912917378457
        },
        ["Bonded Ring"] = {
            Price = 12975,
            Image = 98060786753098
        },
        ["Astral Shard"] = {
            Price = 21100,
            Image = 100038108049217
        },
        ["Lush Bouquet"] = {
            Price = 650,
            Image = 120056805438204
        },
        ["Jelly Bunny"] = {
            Price = 800,
            Image = 107784973626391
        },
        ["Evil Eye"] = {
            Price = 925,
            Image = 129205862888417
        },
        ["Mad Pumpkin"] = {
            Price = 3500,
            Image = 138826885906736
        },
        ["Ionic Dryer"] = {
            Price = 3850,
            Image = 120110210717217
        },
        ["Neko Helmet"] = {
            Price = 5750,
            Image = 132163215245467
        },
        ["Christmas Wreath"] = {
            Price = 4236590,
            Image = 118712048502190,
            Winter = true
        },
        ["Heart Locket (Winter)"] = {
            Price = 1133460,
            Image = 135113246104976,
            Winter = true
        },
        ["Genie Lamp (Snow Globe)"] = {
            Price = 204348,
            Image = 102320503955676,
            Winter = true
        },
        ["Gem Signet"] = {
            Price = 14775,
            Image = 129912666283223
        },
        ["Heroic Helmet"] = {
            Price = 48625,
            Image = 110568169111532
        },
        ["Lunar Snake"] = {
            Price = 350,
            Image = 129900489917281
        },
        ["Tama Gadget"] = {
            Price = 450,
            Image = 88495449822467
        },
        ["Holiday Drink"] = {
            Price = 450,
            Image = 96916863101721
        },
        ["Witch Hat"] = {
            Price = 725,
            Image = 86006759042811
        },
        ["Love Potion"] = {
            Price = 2075,
            Image = 97671003668253
        },
        ["Mighty Arm"] = {
            Price = 83750,
            Image = 93713255591577
        },
        ["Flying Broom"] = {
            Price = 2300,
            Image = 80578936666011
        },
        ["Desk Calendar"] = {
            Price = 300,
            Image = 71562015917891
        },
        ["Bow Tie"] = {
            Price = 775,
            Image = 93723610777988
        },
        ["Bunny Muffin"] = {
            Price = 825,
            Image = 136363201399086
        },
        ["Love Candle"] = {
            Price = 1825,
            Image = 80041378326290
        },
        ["Low Rider"] = {
            Price = 5850,
            Image = 97758186725741
        },
        ["Swicc Watch"] = {
            Price = 7850,
            Image = 137132112906168
        },
        ["Magic Potion"] = {
            Price = 14975,
            Image = 136435612518266
        },
        ["Artisan Brick"] = {
            Price = 35000,
            Image = 140034082742841
        },
        ["Bow Tie (Velvet Gold)"] = {
            Price = 1825,
            Image = 138256903306882
        },
        ["Lol Pop (Gold Star)"] = {
            Price = 625,
            Image = 124277132215346
        },
        ["Bunny Muffin (Gold)"] = {
            Price = 900,
            Image = 97062106748354
        },
        ["Love Candle (Golden Glow)"] = {
            Price = 2925,
            Image = 98206793529924
        },
        ["Ionic Dryer (Gold Rush)"] = {
            Price = 7075,
            Image = 88632597422959
        },
        ["Toy Bear (Golden Cub)"] = {
            Price = 7850,
            Image = 84732046125816
        },
        ["Low Rider (Gold Rush)"] = {
            Price = 11025,
            Image = 136599244703288
        },
        ["Swicc Watch (Day Trader)"] = {
            Price = 15050,
            Image = 124331270386425
        },
        ["Magic Potion (Gold Medal)"] = {
            Price = 27025,
            Image = 87627893871017
        },
        ["Artisan Brick (Gold Bar)"] = {
            Price = 76725,
            Image = 123865861636912
        },
        Heart = {
            Price = 15,
            Image = 94413871110931
        },
        ["Evil Eye (8 Ball)"] = {
            Price = 1725,
            Image = 88701765824891
        },
        ["Hanging Star (Black Hole)"] = {
            Price = 3125,
            Image = 122985278153414
        },
        ["Bow Tie (Dark Lord)"] = {
            Price = 3925,
            Image = 112846505169749
        },
        ["Mad Pumpkin (Daredevil)"] = {
            Price = 4600,
            Image = 78540216998331
        },
        ["Record Player (Dark Noir)"] = {
            Price = 5825,
            Image = 103911450905356
        },
        ["Signet Ring (Obsidian)"] = {
            Price = 7975,
            Image = 78257150248469
        },
        ["Swiss Watch (Memory Flash)"] = {
            Price = 11775,
            Image = 76737983942703
        },
        ["Toy Bear (Ursa Major)"] = {
            Price = 22625,
            Image = 79778986588345
        },
        ["Gem Signet (Black Lotus)"] = {
            Price = 34225,
            Image = 121640567580198
        },
        ["Heroic Helmet (Black Thorn)"] = {
            Price = 74075,
            Image = 116004670495676
        },
        ["Loot Bag (Black Purrse)"] = {
            Price = 112050,
            Image = 113087618020129
        },
        ["Loot Bag (Winter)"] = {
            Price = 8612050,
            Image = 93570674479470,
            Winter = true
        },
        ["Cupid Charm (Dryad Heart)"] = {
            Price = 5275,
            Image = 93063373048460
        },
        ["Love Potion (Banana)"] = {
            Price = 8225,
            Image = 85728989108666
        },
        ["Sakura Flower (Sunflower)"] = {
            Price = 12275,
            Image = 86078082445995
        },
        ["Kissed Frog (Lava Leap)"] = {
            Price = 18975,
            Image = 133989934598634
        },
        ["Gem Signet (Elven Shade)"] = {
            Price = 21750,
            Image = 107693345573978
        },
        ["Bonded Ring (Duckling)"] = {
            Price = 31825,
            Image = 126161353079630
        },
        ["Sakura Flower (Flowey)"] = {
            Price = 83225,
            Image = 80917448424534
        },
        ["Astral Shard (Eve\'s Apple)"] = {
            Price = 117250,
            Image = 78295477322201
        },
        ["Precious Peach (Rich Green)"] = {
            Price = 211725,
            Image = 75907455012686
        },
        ["Crystal Ball (Druid Circle)"] = {
            Price = 3125,
            Image = 95097566532024
        },
        ["Gem Signet (Amethyst)"] = {
            Price = 17225,
            Image = 112148373414499
        },
        ["Diamond Ring (Black Hole)"] = {
            Price = 23250,
            Image = 95993240999867
        },
        ["Astral Shard (Bogartite)"] = {
            Price = 29225,
            Image = 110336683186061
        },
        ["Genie Lamp (Lava Lamp)"] = {
            Price = 42875,
            Image = 107002019192507
        },
        ["Ion Gem (Prismatic)"] = {
            Price = 56250,
            Image = 87684615811667
        },
        ["Loot Bag (Conductor)"] = {
            Price = 84225,
            Image = 93781648650452
        },
        ["Mighty Arm (Crystal Fist)"] = {
            Price = 132175,
            Image = 132300271516638
        },
        ["Durov’s Cap (Honey Bee)"] = {
            Price = 305750,
            Image = 82052377779048
        },
        ["Plush Pepe (Hue Jester)"] = {
            Price = 1337250,
            Image = 118751933850428
        },
        ["Plush Pepe (Cozy Galaxy)"] = {
            Price = 7425750,
            Image = 137727982265916
        },
        ["Plush Pepe (Raphael)"] = {
            Price = 13537250,
            Image = 113111668096660,
            OnlyCase = true
        },
        ["Happy Brownie (Raphael)"] = {
            Price = 753250,
            Image = 89037041285266,
            OnlyCase = true
        },
        ["Plush Pepe (Leonardo)"] = {
            Price = 15327440,
            Image = 134611226729197,
            OnlyCase = true
        },
        ["Plush Pepe (Donatello)"] = {
            Price = 11937224,
            Image = 103525063716671,
            OnlyCase = true
        },
        ["Plush Pepe (Ninja Mike)"] = {
            Price = 8825756,
            Image = 121567926003023,
            OnlyCase = true
        },
        ["Plush Pepe (Turtles)"] = {
            Price = 1738341480,
            Image = 81964451076779,
            OnlyCase = true
        },
        ["Mighty Arm (Pizza Pump)"] = {
            Price = 873175,
            Image = 126933356067303,
            OnlyCase = true
        },
        ["Heart Locket (Synthwave)"] = {
            Price = 450275,
            Image = 80689047630734
        },
        ["Heart Locket (White Wolf)"] = {
            Price = 723025,
            Image = 100278495100224
        },
        ["Electric Skull (Terminator)"] = {
            Price = 70225,
            Image = 91558755398072
        },
        ["Mini Oscar (Fiery-Hot)"] = {
            Price = 87550,
            Image = 126755075183749
        },
        ["Artisan Brick (Fight Club)"] = {
            Price = 112400,
            Image = 126572461741675
        },
        ["Heroic Helmet (Cyberpunk)"] = {
            Price = 147250,
            Image = 111990677499000
        },
        ["Nail Bracelet (Interstellar)"] = {
            Price = 197425,
            Image = 138606000910311
        },
        ["Precious Peach (Angelic)"] = {
            Price = 245050,
            Image = 107862617324547
        },
        ["Durov’s Cap (Falcon)"] = {
            Price = 545725,
            Image = 135862166388337
        },
        ["Heart Locket (Cirque)"] = {
            Price = 1135075,
            Image = 128802869851876
        },
        ["Plush Pepe (Emerald Plush)"] = {
            Price = 6985225,
            Image = 140321887609936
        },
        ["Gem Signet (Death Star)"] = {
            Price = 49575,
            Image = 72226095035040
        },
        ["Cupid Charm (Crystal Clear)"] = {
            Price = 3375,
            Image = 114715582944944
        },
        ["Eternal Candle (Bubble Bath)"] = {
            Price = 1775,
            Image = 81466961095804
        },
        ["Love Potion (Ice Queen)"] = {
            Price = 2550,
            Image = 84589099996166
        },
        ["Mad Pumpkin (Frostbite)"] = {
            Price = 6025,
            Image = 70371898537513
        },
        ["Kissed Frog (Ectofrog)"] = {
            Price = 10500,
            Image = 123150615572699
        },
        ["Money Pot"] = {
            Price = 15050,
            Image = 107434495695849,
            OnlyCase = true
        },
        ["Astral Shard (Aquarium)"] = {
            Price = 28950,
            Image = 71542052117237
        },
        ["Precious Peach (Bubbling Blue)"] = {
            Price = 202750,
            Image = 128950373947198
        },
        ["Fresh Socks (Billie Jean)"] = {
            Price = 4465,
            Image = 112451460979123
        },
        ["Low Rider (Neon Nitro)"] = {
            Price = 6025,
            Image = 139230153254727
        },
        ["Toy Bear (Fazbear)"] = {
            Price = 8350,
            Image = 98257908314760
        },
        ["Electric Skull (Half Alive)"] = {
            Price = 13750,
            Image = 117988848592055
        },
        ["Bonded Ring (Rainbow)"] = {
            Price = 21075,
            Image = 100890727051977
        },
        ["Astral Shard (Nectarite)"] = {
            Price = 37050,
            Image = 129231721446869
        },
        ["Loot Bag (City Life)"] = {
            Price = 74750,
            Image = 95107334963225
        },
        ["Gem Signet (8 Bit Diamond)"] = {
            Price = 105275,
            Image = 97542651728038
        },
        ["Heroic Helmet (Punk Skull)"] = {
            Price = 261750,
            Image = 108709183866571
        },
        ["Durov’s Cap (Sky High)"] = {
            Price = 374025,
            Image = 87734989418118
        },
        ["Gem Signet (Old Bronze)"] = {
            Price = 18250,
            Image = 127419114582578
        },
        ["Bonded Ring (Cat Bed)"] = {
            Price = 22725,
            Image = 108056320202584
        },
        ["Resistance Dog"] = {
            Price = 36250,
            Image = 99469763052004
        },
        ["Nail Bracelet (Cat Person)"] = {
            Price = 52500,
            Image = 116497789375692
        },
        ["Scared Cat (Obelisk)"] = {
            Price = 61125,
            Image = 80736223072883
        },
        ["Nail Bracelet (Moon Cat)"] = {
            Price = 74725,
            Image = 134542847362404
        },
        ["Genie Lamp (Cat Spirit)"] = {
            Price = 82050,
            Image = 133645248773348
        },
        ["Artisan Brick (Cash Roll)"] = {
            Price = 102050,
            Image = 135938823078667
        },
        ["Durov’s Cap (Fun Time)"] = {
            Price = 232775,
            Image = 127588929140653
        },
        ["Heart Locket (Fairy Dust)"] = {
            Price = 637025,
            Image = 74608390316234
        },
        ["Plush Pepe (Poison Dart)"] = {
            Price = 1205075,
            Image = 101726083521374
        },
        ["Plush Pepe (Midas Pepe)"] = {
            Price = 10086725,
            Image = 113532756565274
        },
        ["Toy Bear (Alter Ego)"] = {
            Price = 15525,
            Image = 132946772709069
        },
        ["Scared Cat (Cathulhu)"] = {
            Price = 35175,
            Image = 102920549469289
        },
        ["Genie Lamp (Star Dust)"] = {
            Price = 71250,
            Image = 111922599060513
        },
        ["Loot Bag (Road Trip)"] = {
            Price = 104625,
            Image = 82115090030411
        },
        ["Perfume Bottle (Rose Thorn)"] = {
            Price = 313875,
            Image = 137235451453670
        },
        ["Perfume Bottle (Blizzard)"] = {
            Price = 615370,
            Image = 86627172092775,
            Winter = true
        },
        ["Ionic Dryer (Arc Reactor)"] = {
            Price = 24150,
            Image = 79647360457092
        },
        ["Signet Ring (Saturn Ring)"] = {
            Price = 47250,
            Image = 99588827382352
        },
        ["Astral Shard (Barbed)"] = {
            Price = 90075,
            Image = 131545691607192
        },
        ["Bonded Ring (Asteroid)"] = {
            Price = 111825,
            Image = 101444241107879
        },
        ["Lucky Toy Bear"] = {
            Price = 50550,
            Image = 125686846879641,
            OnlyCase = true
        },
        ["Nail Bracelet (Crypto Gem)"] = {
            Price = 248775,
            Image = 137898270908435
        },
        ["Magic Potion (Error Elixir)"] = {
            Price = 339675,
            Image = 72055525294184
        },
        ["Precious Peach (Crypto Orange)"] = {
            Price = 981900,
            Image = 85185103316683
        },
        ["Clover Pin (Corrupted)"] = {
            Price = 475,
            Image = 107966287910110
        },
        ["Jack in the box (Aliens)"] = {
            Price = 675,
            Image = 126163350570760
        },
        ["Jolly Chimp (Retro Cartoon)"] = {
            Price = 1150,
            Image = 119117358657095
        },
        ["Easter Egg (Creeper)"] = {
            Price = 1425,
            Image = 112986111317442
        },
        ["Ginger Cookie (Headless)"] = {
            Price = 2350,
            Image = 90636761629828
        },
        ["Easter Egg (Boiled Pepe)"] = {
            Price = 3025,
            Image = 102328558025040
        },
        ["Hanging Star (This Is Fine)"] = {
            Price = 8150,
            Image = 74258730609060
        },
        ["Jester Hat (Pepe Hop)"] = {
            Price = 14825,
            Image = 83574927561249
        },
        ["Bonded Ring (Pixel Loot)"] = {
            Price = 19250,
            Image = 118773074715155
        },
        ["Toy Bear (Dark Knight)"] = {
            Price = 30325,
            Image = 123406506624694
        },
        ["Mighty Arm (Gladiator)"] = {
            Price = 133200,
            Image = 120261301863934
        },
        ["Mighty Arm (Icebreaker)"] = {
            Price = 433200,
            Image = 104392759264249,
            Winter = true
        },
        ["Durov’s Cap (Sunrise)"] = {
            Price = 237050,
            Image = 89653743155557
        },
        ["Artisan Brick (USBrick)"] = {
            Price = 360500,
            Image = 111275606025621
        },
        ["Durov’s Cap (RGB Glitch)"] = {
            Price = 1075025,
            Image = 114077822833278
        },
        ["Plush Pepe (Aqua Plush)"] = {
            Price = 3625000,
            Image = 79951247536709
        },
        ["Plush Pepe (Toading...)"] = {
            Price = 58350025,
            Image = 100876384006704
        },
        ["Heart Locket (Saturn)"] = {
            Price = 1086750,
            Image = 91569456729252
        },
        ["Loot Bag (Pepe Bag)"] = {
            Price = 489075,
            Image = 110774067297922
        },
        ["Durov’s Cap (Shadow)"] = {
            Price = 225000,
            Image = 120106320669763
        },
        ["Heart Locket (Trapped Heart)"] = {
            Price = 1462500,
            Image = 95812874555802
        },
        ["Astral Shard (Crystal Punk)"] = {
            Price = 31250,
            Image = 125851623852889
        },
        ["Mighty Arm (Body Builder)"] = {
            Price = 40750,
            Image = 120890942062764
        },
        ["Artisan Brick (Bomb Planted)"] = {
            Price = 63025,
            Image = 73938343268549
        },
        ["Cupid Charm (Pepe Love)"] = {
            Price = 87050,
            Image = 124793048061468
        },
        ["Precious Peach (Yin Yang)"] = {
            Price = 162325,
            Image = 82566017184658
        },
        ["Durov’s Cap (Neon)"] = {
            Price = 348750,
            Image = 94017660028407
        },
        ["Heart Locket (Neptune)"] = {
            Price = 888750,
            Image = 108036969074269
        },
        ["Loot Bag (Crypto Byte)"] = {
            Price = 113750,
            Image = 93824242357401
        },
        ["Artisan Brick (Gold Block)"] = {
            Price = 157025,
            Image = 137657331614013
        },
        ["Heroic Helmet (Frozen Aegis)"] = {
            Price = 230325,
            Image = 72071945981785
        },
        ["Heart Locket (Shield of Sun)"] = {
            Price = 623500,
            Image = 95803458445365
        },
        ["Heart Locket (Delegram)"] = {
            Price = 986250,
            Image = 121149571015496
        },
        ["Plush Pepe (Amalgam)"] = {
            Price = 1625025,
            Image = 78541215824890
        },
        ["Durov’s Cap (Tron)"] = {
            Price = 398025,
            Image = 96218385452442
        },
        ["Heart Locket (Mecha Love)"] = {
            Price = 600000,
            Image = 121613071294644
        },
        ["Plush Pepe (Gucci Leap)"] = {
            Price = 237725750,
            Image = 100119527019858,
            OnlyCase = true
        },
        ["Plush Pepe (Frozen)"] = {
            Price = 248625290,
            Image = 134520261467083,
            OnlyCase = true,
            Winter = true
        },
        ["Plush Pepe (Christmas)"] = {
            Price = 7168531235,
            Image = 114032869163843,
            Winter = true
        },
        ["Plush Pepe (X-Ray)"] = {
            Price = 1000206225,
            Image = 97482516290784,
            OnlyCase = true
        },
        ["Artisan Brick (Concrete)"] = {
            Price = 41250,
            Image = 107695062002543
        },
        ["Heroic Helmet (Praetorian)"] = {
            Price = 74025,
            Image = 88085994202813
        },
        ["Precious Peach (Peach Black)"] = {
            Price = 110725,
            Image = 134492875974846
        },
        ["Heart Locket (Nightclub)"] = {
            Price = 607050,
            Image = 138890353250169
        },
        ["Plush Pepe (Emo Boi)"] = {
            Price = 5036225,
            Image = 122823830749644
        },
        ["Heart Locket (Turtles)"] = {
            Price = 12330325,
            Image = 79070451467980,
            OnlyCase = true
        },
        ["Plush Pepe (Pink Galaxy)"] = {
            Price = 5928744750,
            Image = 119733269901388,
            OnlyCase = true,
            Unique = true
        },
        ["Durov’s Figurine"] = {
            Price = 160256075,
            Image = 94005630449413,
            OnlyCase = true
        },
        ["Durov’s Figurine (X-Ray)"] = {
            Price = 410256075,
            Image = 120477288435481,
            OnlyCase = true
        },
        ["Durov’s Sunglasses"] = {
            Price = 13178050,
            Image = 74435088975390,
            OnlyCase = true
        },
        ["Durov’s Coat"] = {
            Price = 840325,
            Image = 72958250731974,
            OnlyCase = true
        },
        ["Durov’s Boots"] = {
            Price = 170625,
            Image = 128134854871653,
            OnlyCase = true
        },
        ["Plush Pepe (Steel Frog)"] = {
            Price = 1583075550,
            Image = 86913280986289,
            OnlyCase = true
        },
        ["Bling Binky (Tribal Skull)"] = {
            Price = 78025,
            Image = 139734247031615,
            OnlyCase = true
        },
        ["Westside Sign (Sapphire)"] = {
            Price = 107625,
            Image = 101575717524437
        },
        ["Pink Flamingo"] = {
            Price = 189250,
            Image = 82738481564743,
            OnlyCase = true
        },
        ["Crystal Eagle"] = {
            Price = 4905850225,
            Image = 110412295968493,
            OnlyCase = true
        },
        ["Plush Pepe (Magnate)"] = {
            Price = 924760275,
            Image = 125949078829489,
            OnlyCase = true
        },
        ["Gem Signet (Spinny Boi)"] = {
            Price = 10782203050,
            Image = 75036682111753,
            OnlyCase = true
        },
        ["Plush Pepe (Kung Fu Pepe)"] = {
            Price = 3074895775,
            Image = 126825154830683
        },
        ["Input Key (Angel)"] = {
            Price = 2625,
            Image = 139639729233565
        },
        ["Toy Bear (Angel)"] = {
            Price = 16250,
            Image = 132024367329471
        },
        ["Telegram Pin"] = {
            Price = 8525000000,
            Image = 85194869805750,
            OnlyCase = true,
            DisplayName = "TG Pin"
        },
        ["Telegram Pin (Gradient)"] = {
            Price = 60888888000,
            Image = 73975269431953,
            OnlyCase = true,
            DisplayName = "TG Pin (Gradient)"
        },
        ["Plush Pepe (Clown)"] = {
            Price = 77777777777,
            Image = 82739431415394,
            OnlyCase = true
        },
        ["Plush Pepe (Santa)"] = {
            Price = 2223765134,
            Image = 133122895457327,
            Winter = true
        },
        ["Plush Pepe (Hothead)"] = {
            Price = 846461046,
            Image = 130639104288631,
            OnlyCase = true
        },
        ["Mini Oscar (Claus)"] = {
            Price = 40655413,
            Image = 100722771607414,
            Winter = true
        },
        ["Precious Peach (Xmas Lights)"] = {
            Price = 825414237,
            Image = 106888952696850,
            Winter = true
        },
        ["Loot Bag (Glacier)"] = {
            Price = 556534891,
            Image = 88237807065894,
            Winter = true
        },
        ["Khabib\'s Papakha (Winter)"] = {
            Price = 394376549,
            Image = 73770789197363,
            Winter = true
        },
        ["Neko Helmet (Frostbear)"] = {
            Price = 239543128,
            Image = 97818651133991,
            Winter = true
        },
        ["Telegram Pin (Christmas)"] = {
            Price = 75014777777,
            Image = 106906356643360,
            OnlyCase = true,
            Winter = true,
            DisplayName = "TG Pin (Christmas)"
        },
        ["Gem Signet (XMAS Spinny Boi)"] = {
            Price = 104013245783,
            Image = 122255461326468,
            OnlyCase = true,
            Winter = true
        },
        ["Christmas Tree"] = {
            Price = 7002026,
            Image = 70875484033160,
            Winter = true
        },
        ["Ginger Cookie (Claus)"] = {
            Price = 25145,
            Image = 103663121436788,
            Winter = true
        },
        ["Sharp Tongue (Frostbite)"] = {
            Price = 47832,
            Image = 135314802530625,
            Winter = true
        },
        ["Bling Binky (Christmas)"] = {
            Price = 89541,
            Image = 113264363320600,
            Winter = true
        },
        ["Resistance Dog (Christmas)"] = {
            Price = 17777777777,
            Image = 79640819093733,
            Winter = true,
            OnlyCase = true
        },
        ["Crystal Eagle (Jolly)"] = {
            Price = 202620262026,
            Image = 112656716312785,
            Winter = true,
            OnlyCase = true
        },
        ["XMAS Stocking (Heaven)"] = {
            Price = 1111111,
            Image = 92688670102580
        },
        ["Ionic Dryer (Angel Blast)"] = {
            Price = 9999999,
            Image = 138036370306768
        },
        ["Top Hat (Celestial)"] = {
            Price = 17777777,
            Image = 90014097824875
        },
        ["Sleigh Ball (Holy Grenade)"] = {
            Price = 4444444444,
            Image = 72325208376473,
            OnlyCase = true
        },
        ["Loot Bag (Priestly)"] = {
            Price = 7777777777,
            Image = 91815335328119,
            OnlyCase = true
        },
        ["Resistance Dog (Holy Dog)"] = {
            Price = 22222222222,
            Image = 92581372778932,
            OnlyCase = true
        },
        Liberty = {
            Price = 405156,
            Image = 105471133542857,
            OnlyCase = true
        },
        ["Bow Tie (Durov\'s Dog)"] = {
            Price = 1502659,
            Image = 127715395741623,
            OnlyCase = true
        },
        ["Joyful Bundle (Gem Stash)"] = {
            Price = 38145769,
            Image = 132252466731341,
            OnlyCase = true
        },
        ["Tama Gadget (Underdog)"] = {
            Price = 3659561518,
            Image = 87232032101980,
            OnlyCase = true
        },
        ["Nail Bracelet (Resistance)"] = {
            Price = 44954431645,
            Image = 110285578518898,
            OnlyCase = true
        },
        ["Toy Bear (Christmas)"] = {
            Price = 5002026,
            Image = 119765450131909,
            OnlyCase = true,
            Winter = true
        },
        ["Trojan Horse"] = {
            Price = 821538,
            Image = 77918389402075
        },
        ["Toy Bear (Spring)"] = {
            Price = 80000,
            Image = 97273581947301
        },
        ["Toy Bear (Valentine)"] = {
            Price = 1400260,
            Image = 132800952372805
        },
        ["Valentine Heart"] = {
            Price = 1415380,
            Image = 99079851596499
        },
        ["Desk Calendar (Lovely)"] = {
            Price = 1241355,
            Image = 84210626044717,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Gold Leaf)"] = {
            Price = 1341355,
            Image = 138299476694878,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Tropical)"] = {
            Price = 1351355,
            Image = 116848967037413,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Orange Mood)"] = {
            Price = 1441355,
            Image = 113387874705805,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Purple Mint)"] = {
            Price = 1451355,
            Image = 127407922948313,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Blue Sky)"] = {
            Price = 1461355,
            Image = 127448220159836,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Golden Touch)"] = {
            Price = 1561355,
            Image = 119070506494882,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Minting Date)"] = {
            Price = 1581355,
            Image = 81273441529894,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Lavendays)"] = {
            Price = 1781355,
            Image = 91602760607042,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Harvest)"] = {
            Price = 1881355,
            Image = 72246053516114,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (October)"] = {
            Price = 10081355,
            Image = 125946452266818,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (November)"] = {
            Price = 12061355,
            Image = 89597913254727,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (December)"] = {
            Price = 13061355,
            Image = 87173163096816,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Golden Years)"] = {
            Price = 15081355,
            Image = 77612710850041,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Thursday)"] = {
            Price = 18081355,
            Image = 133719087969132,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (September)"] = {
            Price = 50081355,
            Image = 95869682800550,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (March)"] = {
            Price = 67061355,
            Image = 108867045532499,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Saturday)"] = {
            Price = 75061355,
            Image = 120441303177458,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (June)"] = {
            Price = 28081355,
            Image = 91571967726831,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (April)"] = {
            Price = 39081355,
            Image = 82358682328142,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Durov Day)"] = {
            Price = 200081355,
            Image = 116296833942033,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Pepe Plans)"] = {
            Price = 257061355,
            Image = 90024135079312,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Burning Time)"] = {
            Price = 285061355,
            Image = 78384345269413,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Fund Manager)"] = {
            Price = 325061355,
            Image = 86212933390805,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Investor)"] = {
            Price = 345061355,
            Image = 110315757431080,
            OnlyCase = true,
            Craftable = true
        },
        ["Desk Calendar (Óðinsdagr)"] = {
            Price = 56241355080,
            Image = 95689495522047,
            Crafted = true,
            CraftChance = 0.1
        },
        ["Desk Calendar (Day of Mars)"] = {
            Price = 51852400315,
            Image = 73552455265093,
            Crafted = true,
            CraftChance = 0.1
        },
        ["Desk Calendar (Celestial Map)"] = {
            Price = 43406135540,
            Image = 106253238384221,
            Crafted = true,
            CraftChance = 0.1
        },
        ["Desk Calendar (Loki\'s Day)"] = {
            Price = 40508135500,
            Image = 101750918330447,
            Crafted = true,
            CraftChance = 0.1
        },
        ["Desk Calendar (May the Fourth)"] = {
            Price = 38408135500,
            Image = 122659186857593,
            Crafted = true,
            CraftChance = 0.1
        },
        ["Desk Calendar (Aphrodite)"] = {
            Price = 17081355120,
            Image = 133433576957769,
            Crafted = true,
            CraftChance = 0.2
        },
        ["Desk Calendar (Selena)"] = {
            Price = 16206135500,
            Image = 122118538125417,
            Crafted = true,
            CraftChance = 0.2
        },
        ["Desk Calendar (Týsdagr)"] = {
            Price = 15081355820,
            Image = 98940361495245,
            Crafted = true,
            CraftChance = 0.25
        },
        ["Desk Calendar (Frjádagr)"] = {
            Price = 14061355340,
            Image = 137977100331131,
            Crafted = true,
            CraftChance = 0.25
        },
        ["Desk Calendar (Þórsdagr)"] = {
            Price = 13081355000,
            Image = 130246661363460,
            Crafted = true,
            CraftChance = 0.3
        },
        ["Desk Calendar (TON Core)"] = {
            Price = 12250613550,
            Image = 81074230399661,
            Crafted = true,
            CraftChance = 0.3
        },
        ["Desk Calendar (Kronos)"] = {
            Price = 11081355410,
            Image = 85096808599059,
            Crafted = true,
            CraftChance = 0.3
        },
        ["Desk Calendar (Sol Invictus)"] = {
            Price = 9081355200,
            Image = 122855133263161,
            Crafted = true,
            CraftChance = 0.35
        },
        ["Desk Calendar (Shinto Shrine)"] = {
            Price = 8061355650,
            Image = 92490397747680,
            Crafted = true,
            CraftChance = 0.35
        },
        ["Desk Calendar (Lucky Day)"] = {
            Price = 7081355130,
            Image = 79069929820961,
            Crafted = true,
            CraftChance = 0.4
        },
        ["Desk Calendar (Mánadagr)"] = {
            Price = 6206135500,
            Image = 139298595536360,
            Crafted = true,
            CraftChance = 0.4
        },
        ["Desk Calendar (Treasure Map)"] = {
            Price = 5581355910,
            Image = 99187808753074,
            Crafted = true,
            CraftChance = 0.4
        },
        ["Desk Calendar (Royal Flush)"] = {
            Price = 5061355040,
            Image = 109583845584101,
            Crafted = true,
            CraftChance = 0.5
        },
        ["Desk Calendar (Frog Day)"] = {
            Price = 2508135512,
            Image = 135647595860277,
            Crafted = true,
            CraftChance = 1
        },
        ["Desk Calendar (First Date)"] = {
            Price = 2406135580,
            Image = 113922724222006,
            Crafted = true,
            CraftChance = 1.1
        },
        ["Desk Calendar (Payday)"] = {
            Price = 2258135525,
            Image = 129031428233839,
            Crafted = true,
            CraftChance = 1.2
        },
        ["Desk Calendar (Grimoire)"] = {
            Price = 2106135540,
            Image = 75713976934181,
            Crafted = true,
            CraftChance = 1.3
        },
        ["Desk Calendar (Cat Seasons)"] = {
            Price = 2008135505,
            Image = 93210416532311,
            Crafted = true,
            CraftChance = 1.4
        },
        ["Desk Calendar (Ghost Party)"] = {
            Price = 1808135515,
            Image = 96614254743993,
            Crafted = true,
            CraftChance = 1.4
        },
        ["Desk Calendar (Zeus)"] = {
            Price = 1656135590,
            Image = 88864815154316,
            Crafted = true,
            CraftChance = 1.4
        },
        ["Desk Calendar (Samhain)"] = {
            Price = 1356135560,
            Image = 111700550836056,
            Crafted = true,
            CraftChance = 1.5
        },
        ["Desk Calendar (Hermes)"] = {
            Price = 1208135520,
            Image = 88241634096025,
            Crafted = true,
            CraftChance = 1.5
        },
        ["Desk Calendar (Count Dracula)"] = {
            Price = 1006135585,
            Image = 95622176301356,
            Crafted = true,
            CraftChance = 1.5
        },
        ["Desk Calendar (Sekhmet)"] = {
            Price = 390613550,
            Image = 127046522705255,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Cyberpunk)"] = {
            Price = 380813558,
            Image = 133153413782307,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Anniversary)"] = {
            Price = 370613551,
            Image = 87263652359600,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Crunch Time)"] = {
            Price = 360813554,
            Image = 123710238466679,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Mesozoic)"] = {
            Price = 350613559,
            Image = 136222220410336,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Orchestra)"] = {
            Price = 340813550,
            Image = 110000724382686,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Daily Bread)"] = {
            Price = 330613552,
            Image = 96937036339326,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Helios)"] = {
            Price = 320813557,
            Image = 71060365549894,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Steampunk)"] = {
            Price = 310613553,
            Image = 127828321409537,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Holy Month)"] = {
            Price = 280813554,
            Image = 70934364258044,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Anno Domini)"] = {
            Price = 270613559,
            Image = 98529569105920,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (New Year)"] = {
            Price = 260813550,
            Image = 113574472349586,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Vacation)"] = {
            Price = 250613557,
            Image = 123986128674909,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Shopping List)"] = {
            Price = 240813552,
            Image = 136127172087114,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (April Fools)"] = {
            Price = 230613558,
            Image = 126461535238830,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Women\'s Day)"] = {
            Price = 220813551,
            Image = 87852861999956,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Vintage)"] = {
            Price = 210613554,
            Image = 88895125939097,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Yoga Time)"] = {
            Price = 190813559,
            Image = 81606909474269,
            Crafted = true,
            CraftChance = 15
        },
        ["Desk Calendar (Toy Calendar)"] = {
            Price = 150613550,
            Image = 92459619950644,
            Crafted = true,
            CraftChance = 15
        },
        ["Plush Pepe (Kitty)"] = {
            Price = 8900813559,
            Image = 82281014970839,
            OnlyCase = true
        },
        ["Precious Peach (Glossy Pink)"] = {
            Price = 3541769054,
            Image = 139796302478397,
            OnlyCase = true
        },
        ["Plush Pepe (Dark Pink)"] = {
            Price = 6541669084,
            Image = 99579513843118,
            OnlyCase = true
        },
        ["Nail Bracelet (Rose Thorn)"] = {
            Price = 1541469034,
            Image = 126703919696933,
            OnlyCase = true
        },
        ["Lush Bouquet (Million Roses)"] = {
            Price = 831515869,
            Image = 80604222517199,
            OnlyCase = true
        },
        ["Astral Shard (Lovestone)"] = {
            Price = 458105416,
            Image = 89030446583597,
            OnlyCase = true
        },
        ["Kissed Frog (Pond Fairy)"] = {
            Price = 205156859,
            Image = 116430116035935,
            OnlyCase = true
        },
        ["Pool Float (Show Seal)"] = {
            Price = 389892,
            Image = 116076004170535,
            OnlyCase = true,
            Summer = true
        },
        ["Pool Float (Sebastian)"] = {
            Price = 965634,
            Image = 123462294524910,
            OnlyCase = true,
            Summer = true
        },
        ["Pool Float (Palm Beach)"] = {
            Price = 3523547,
            Image = 85211826426509,
            OnlyCase = true,
            Summer = true
        },
        ["Pool Float (Pool Pepe)"] = {
            Price = 25358892,
            Image = 83402339286249,
            OnlyCase = true,
            Summer = true
        },
        ["Pool Float (Duck Boss)"] = {
            Price = 46693396,
            Image = 102786460500454,
            OnlyCase = true,
            Summer = true
        },
        ["Pool Float (Crypto Whale)"] = {
            Price = 141245479,
            Image = 82999818917491,
            OnlyCase = true,
            Summer = true
        },
        ["Pool Float (Safari)"] = {
            Price = 2468243836,
            Image = 105894157364680,
            OnlyCase = true,
            Summer = true
        },
        ["Plush Pepe (Tropical)"] = {
            Price = 17777777777,
            Image = 73849783332784,
            OnlyCase = true,
            Summer = true
        },
        ["Telegram Pin (Tropical)"] = {
            Price = 225585000000,
            Image = 92835421199871,
            OnlyCase = true,
            Summer = true,
            DisplayName = "TG Pin (Tropical)"
        },
        ["Resistance Dog (Summer)"] = {
            Price = 28790000000,
            Image = 134002537190959,
            OnlyCase = true,
            Summer = true,
            DisplayName = "REDO (Summer)"
        },
        ["Durov’s Boots (Slippers)"] = {
            Price = 692575000,
            Image = 120323947972730,
            OnlyCase = true,
            Summer = true
        },
        ["Durov’s Figurine (Surfer)"] = {
            Price = 72485675000,
            Image = 84811832300085,
            OnlyCase = true,
            Summer = true
        },
        ["Toy Bear (May 1)"] = {
            Price = 50,
            Image = 83941558049496,
            OnlyCase = true,
            Summer = true
        },
        ["Plush Pepe (Bavaria)"] = {
            Price = 10412223234,
            Image = 77763058474998,
            OnlyCase = true
        },
        ["Durov’s Figurine (Ilon)"] = {
            Price = 3746634265,
            Image = 132683982496229
        },
        ["Pool Float (Nessie)"] = {
            Price = 793356832,
            Image = 105242209346125
        },
        ["Happy Brownie (Toilet Bot)"] = {
            Price = 52228677,
            Image = 119297956679055
        },
        ["Mood Pack (Bank Vault)"] = {
            Price = 3124789,
            Image = 72362821432946
        },
        ["Toy Bear (Blueprint)"] = {
            Price = 1536235,
            Image = 96772182407103
        },
        ["Genie Lamp (Monstrous)"] = {
            Price = 14457000,
            Image = "117005029161773"
        },
        ["Perfume Bottle (Noir)"] = {
            Price = 41407200,
            Image = "74627141535362"
        },
        ["Nail Bracelet (Shadow)"] = {
            Price = 116470200,
            Image = "108007070959272"
        },
        ["Astral Shard (Dark Soul)"] = {
            Price = 364927800,
            Image = "116601471347163"
        },
        ["Timeless Book (Death Note)"] = {
            Price = 18066006600,
            Image = "74304923913289",
            OnlyCase = true
        },
        ["Perfume Bottle (Venom Mist)"] = {
            Price = 13925600,
            Image = "129802406577846"
        },
        ["Magic Potion (Verdant Vial)"] = {
            Price = 18084800,
            Image = "102511644282252"
        },
        ["Astral Shard (Uranium)"] = {
            Price = 25280800,
            Image = "119399335853916"
        },
        ["Genie Lamp (Lost Souls)"] = {
            Price = 33610400,
            Image = "74751085568125"
        },
        ["Precious Peach (Gleam Bite)"] = {
            Price = 53736000,
            Image = "82670066000286"
        },
        ["Durov’s Cap (Toxic Guy)"] = {
            Price = 113351200,
            Image = "80009238342246"
        },
        ["Heart Locket (Reactor)"] = {
            Price = 217603200,
            Image = "121824522772517",
            OnlyCase = true
        },
        ["Crystal Eagle (Sakura)"] = {
            Price = 43087525065,
            Image = "87588897981605",
            Summer = true,
            OnlyCase = true
        },
        ["Heart Locket (Sakura)"] = {
            Price = 5773025445,
            Image = "122429150066378",
            Summer = true
        },
        ["Gift Durov’s Cap (Sakura)"] = {
            Price = 1033457030,
            Image = "86621323929476",
            Summer = true
        },
        ["Nail Bracelet (Sakura)"] = {
            Price = 457012070,
            Image = "123772517520948",
            Summer = true
        },
        ["Mood Pack (Sakura)"] = {
            Price = 301896155,
            Image = "90458415647864",
            Summer = true
        },
        ["Durov’s Figurine (Holidays)"] = {
            Price = 1714569955,
            Image = "108105110783728",
            Summer = true,
            OnlyCase = true
        },
        ["Durov’s Sunglasses (Tropics)"] = {
            Price = 598450110,
            Image = "79182517046170",
            Summer = true
        },
        ["Surfboard (Tropics)"] = {
            Price = 98895060,
            Image = "123072288877784",
            Summer = true
        },
        ["Ion Gem (Sea)"] = {
            Price = 37081800,
            Image = "92538901237394",
            Summer = true
        },
        ["Coconut (Tropics)"] = {
            Price = 5573095,
            Image = "109757119257010",
            Summer = true
        },
        ["Plush Pepe (Sandy)"] = {
            Price = 4513366015,
            Image = "116360209575635",
            Summer = true,
            OnlyCase = true
        },
        ["Artisan Brick (Pyramid)"] = {
            Price = 1589999040,
            Image = "84693365202430",
            Summer = true
        },
        ["Mighty Arm (Desert)"] = {
            Price = 400573035,
            Image = "107367690934526",
            Summer = true
        },
        ["Magic Potion (Sandy)"] = {
            Price = 158400235,
            Image = "105379907509578",
            Summer = true
        },
        ["Sandcastle (Desert)"] = {
            Price = 24570055,
            Image = "112922280290974",
            Summer = true
        },
        ["Grim Reaper (Summer)"] = {
            Price = 275555555555,
            Image = "92133539467985",
            Summer = true,
            OnlyCase = true
        },
        ["Resistance Dog (Shark)"] = {
            Price = 395555555555,
            Image = "116909575223311",
            Summer = true,
            OnlyCase = true
        },
        ["Neko Helmet (Shark)"] = {
            Price = 5978455,
            Image = "80979036604960",
            Summer = true
        },
        ["Durov’s Figurine (Homelander)"] = {
            Price = 250555555555,
            Image = "81784014087285",
            OnlyCase = true
        },
        ["Durov’s Figurine (Butcher)"] = {
            Price = 57888888888,
            Image = "81942883662656",
            OnlyCase = true
        },
        ["Durov’s Figurine (Soldier Boy)"] = {
            Price = 12333333333,
            Image = "127317034118548",
            OnlyCase = true
        },
        ["Durov’s Figurine (A-Train)"] = {
            Price = 4666666666,
            Image = "120679700562476",
            OnlyCase = true
        },
        ["Durov’s Figurine (The Deep)"] = {
            Price = 1777777777,
            Image = "103288400857684",
            OnlyCase = true
        },
        ["Durov’s Figurine (Dio)"] = {
            Price = 577777777777,
            Image = "119556664889659",
            OnlyCase = true
        },
        ["Durov’s Figurine (Ronaldo)"] = {
            Price = 777777777777,
            Image = "100374134815959",
            OnlyCase = true
        },
        ["Trophy (Championship)"] = {
            Price = 2026202620,
            Image = "78840999828262",
            OnlyCase = true
        },
        ["Plush Pepe (Captain)"] = {
            Price = 300000000000,
            Image = "79341926061544",
            OnlyCase = true
        },
        ["Heart Locket (Deadpool)"] = {
            Price = 5555555555,
            Image = "81675313862774\t",
            OnlyCase = true
        },
        ["Mini Oscar (Spidey)"] = {
            Price = 175760041,
            Image = "81943261290290",
            OnlyCase = true
        },
        ["Mighty Arm (Infinity)"] = {
            Price = 333333333,
            Image = "104889727539203",
            OnlyCase = true
        },
        ["Gem Signet (Arc Reactor)"] = {
            Price = 267054323,
            Image = "72102212760216",
            OnlyCase = true
        },
        ["Khabib\'s Papakha (Madridista)"] = {
            Price = 989140000,
            Image = "88575331919518",
            OnlyCase = true
        },
        ["Victory Medal (Glory Goal)"] = {
            Price = 45120067,
            Image = "111646242760814",
            OnlyCase = true
        },
        ["Blink Blinky (Soccer)"] = {
            Price = 676767676,
            Image = "77145020543855",
            OnlyCase = true
        },
        ["Mini Oscar (The World)"] = {
            Price = 7777777777,
            Image = "117775493636731",
            OnlyCase = true
        },
        ["Mask (Stone Mask)"] = {
            Price = 17777777,
            Image = "130745893086113",
            OnlyCase = true
        },
        ["Toy Bear (Natsuki)"] = {
            Price = 999999999999,
            Image = "139778265038718",
            OnlyCase = true,
            Hidden = true
        },
        ["Case (TSUM)"] = {
            Price = 1000000000000,
            Image = "82109193707885",
            OnlyCase = true
        },
        ["Resistance Dog (Drill Fit)"] = {
            Price = 175856449750,
            Image = "138356714623112",
            OnlyCase = true
        },
        ["Mood Pack (BAPE)"] = {
            Price = 25478125050,
            Image = "97096516277734",
            OnlyCase = true
        },
        ["Gift Durov’s Cap (Arctic)"] = {
            Price = 4523719525,
            Image = "139357681263099",
            OnlyCase = true
        }
    },
    Cases = {
        TSUM = {
            Price = 999999999,
            Image = "122507805641975",
            Drop = {
                { "Case (TSUM)", 0.01 },
                { "Resistance Dog (Drill Fit)", 0.09 },
                { "Mood Pack (BAPE)", 0.7 },
                { "Gift Durov’s Cap (Arctic)", 4.2 },
                { "Heart", 95 }
            }
        },
        Dio = {
            Price = 577777777,
            Image = "123317710551278",
            Drop = {
                { "Durov’s Figurine (Dio)", 0.015 },
                { "Mini Oscar (The World)", 3.475 },
                { "Mask (Stone Mask)", 96.5 }
            }
        },
        ["The Boys"] = {
            Price = 1500,
            GEMS = true,
            Image = "70923515271544",
            Drop = {
                { "Durov’s Figurine (Homelander)", 0.1 },
                { "Durov’s Figurine (Butcher)", 0.7 },
                { "Durov’s Figurine (Soldier Boy)", 5.2 },
                { "Durov’s Figurine (A-Train)", 24 },
                { "Durov’s Figurine (The Deep)", 70 }
            }
        },
        ["Shark Bite"] = {
            Price = 3000,
            SUN = true,
            Image = "88953792967652",
            Drop = {
                { "Resistance Dog (Shark)", 1 },
                { "Neko Helmet (Shark)", 99 }
            }
        },
        Desert = {
            Price = 250,
            SUN = true,
            Image = "74029859605294",
            Drop = {
                { "Plush Pepe (Sandy)", 0.5 },
                { "Artisan Brick (Pyramid)", 1.75 },
                { "Mighty Arm (Desert)", 7 },
                { "Magic Potion (Sandy)", 20 },
                { "Sandcastle (Desert)", 70.75 }
            }
        },
        Tropical = {
            Price = 100,
            SUN = true,
            Image = "92036367409033",
            Drop = {
                { "Durov’s Figurine (Holidays)", 1 },
                { "Durov’s Sunglasses (Tropics)", 2.5 },
                { "Surfboard (Tropics)", 10 },
                { "Ion Gem (Sea)", 20 },
                { "Coconut (Tropics)", 66.5 }
            }
        },
        ["Blooming Sakura"] = {
            Price = 1000,
            SUN = true,
            Image = "94649364884706",
            Drop = {
                { "Crystal Eagle (Sakura)", 0.5 },
                { "Heart Locket (Sakura)", 2.5 },
                { "Gift Durov’s Cap (Sakura)", 7 },
                { "Nail Bracelet (Sakura)", 30 },
                { "Mood Pack (Sakura)", 60 }
            }
        },
        Radioactive = {
            Price = 24999999,
            Image = "110824486039912",
            Drop = {
                { "Perfume Bottle (Venom Mist)", 60.1 },
                { "Magic Potion (Verdant Vial)", 20 },
                { "Astral Shard (Uranium)", 10 },
                { "Genie Lamp (Lost Souls)", 5 },
                { "Precious Peach (Gleam Bite)", 2 },
                { "Durov’s Cap (Toxic Guy)", 1.9 },
                { "Heart Locket (Reactor)", 1 }
            }
        },
        Cirque = {
            Image = 102198691984946,
            Price = 700,
            GEMS = true,
            Drop = {
                { "Plush Pepe (Clown)", 0.1 },
                { "Heart Locket (Cirque)", 29.9 },
                { "Durov’s Cap (Fun Time)", 70 }
            }
        },
        Monarch = {
            Image = 92789602242541,
            Price = 12999999,
            Drop = {
                { "Input Key (Angel)", 80 },
                { "Toy Bear (Angel)", 19.75 },
                { "Plush Pepe (Kung Fu Pepe)", 0.2 },
                { "Crystal Eagle", 0.04 },
                { "Gem Signet (Spinny Boi)", 0.01 }
            }
        },
        Magnate = {
            Image = 123757755758214,
            GEMS = true,
            Price = 500,
            Drop = {
                { "Bling Binky (Tribal Skull)", 41.88 },
                { "Westside Sign (Sapphire)", 33 },
                { "Pink Flamingo", 25 },
                { "Plush Pepe (Magnate)", 0.1 },
                { "Crystal Eagle", 0.02 }
            }
        },
        ["Sunny Day"] = {
            Image = 73024061358319,
            TON = true,
            Price = 15500,
            Drop = {
                { "Pool Float (Show Seal)", 36 },
                { "Pool Float (Sebastian)", 31 },
                { "Pool Float (Palm Beach)", 26 },
                { "Pool Float (Pool Pepe)", 3 },
                { "Pool Float (Duck Boss)", 2.87 },
                { "Pool Float (Crypto Whale)", 0.98 },
                { "Pool Float (Safari)", 0.14 },
                { "Plush Pepe (Tropical)", 0.01 }
            }
        },
        ["Death Note"] = {
            Price = 79750,
            TON = true,
            Image = 98726594446431,
            Drop = {
                { "Genie Lamp (Monstrous)", 47.2 },
                { "Perfume Bottle (Noir)", 24 },
                { "Nail Bracelet (Shadow)", 18.5 },
                { "Astral Shard (Dark Soul)", 10.29 },
                { "Timeless Book (Death Note)", 0.01 }
            }
        },
        ["Desk Calendars"] = {
            Image = 137761401385296,
            Price = 44000000,
            Drop = {
                { "Desk Calendar (Lovely)", 10 },
                { "Desk Calendar (Gold Leaf)", 8 },
                { "Desk Calendar (Tropical)", 8 },
                { "Desk Calendar (Orange Mood)", 8 },
                { "Desk Calendar (Purple Mint)", 6 },
                { "Desk Calendar (Blue Sky)", 6 },
                { "Desk Calendar (Golden Touch)", 6 },
                { "Desk Calendar (Minting Date)", 6 },
                { "Desk Calendar (Lavendays)", 6 },
                { "Desk Calendar (Harvest)", 6 },
                { "Desk Calendar (October)", 4 },
                { "Desk Calendar (November)", 4 },
                { "Desk Calendar (December)", 4 },
                { "Desk Calendar (Golden Years)", 4 },
                { "Desk Calendar (Thursday)", 4 },
                { "Desk Calendar (June)", 2 },
                { "Desk Calendar (April)", 2 },
                { "Desk Calendar (September)", 1.4 },
                { "Desk Calendar (March)", 1.4 },
                { "Desk Calendar (Saturday)", 1.2 },
                { "Desk Calendar (Durov Day)", 0.5 },
                { "Desk Calendar (Pepe Plans)", 0.5 },
                { "Desk Calendar (Burning Time)", 0.4 },
                { "Desk Calendar (Fund Manager)", 0.3 },
                { "Desk Calendar (Investor)", 0.3 }
            }
        },
        Durov = {
            Image = 77154250163489,
            TON = true,
            Price = 1500,
            Drop = {
                { "Durov’s Boots", 75.7 },
                { "Durov’s Coat", 20 },
                { "Durov’s Sunglasses", 4 },
                { "Durov’s Figurine", 0.23 },
                { "Durov’s Figurine (X-Ray)", 0.1 },
                { "Plush Pepe (Steel Frog)", 0.02 }
            }
        },
        REDO = {
            Image = 132457608690149,
            TON = true,
            Price = 47500,
            Drop = {
                { "Liberty", 69.77 },
                { "Bow Tie (Durov\'s Dog)", 25 },
                { "Joyful Bundle (Gem Stash)", 4.99 },
                { "Tama Gadget (Underdog)", 0.22 },
                { "Nail Bracelet (Resistance)", 0.02 }
            }
        },
        Angel = {
            Image = 113027733090291,
            Price = 33333333,
            Drop = {
                { "XMAS Stocking (Heaven)", 57.69 },
                { "Ionic Dryer (Angel Blast)", 25 },
                { "Top Hat (Celestial)", 17 },
                { "Sleigh Ball (Holy Grenade)", 0.2 },
                { "Loot Bag (Priestly)", 0.1 },
                { "Resistance Dog (Holy Dog)", 0.01 }
            }
        },
        ["Last Chance"] = {
            Image = 86067798652378,
            Paid = true,
            Price = 279,
            Drop = {
                { "Witch Hat (Mordor)", 50 },
                { "Mask", 40 },
                { "Coffin", 7 },
                { "Gravestone", 2.5 },
                { "Grim Reaper", 0.5 }
            }
        },
        ["Bloody Night"] = {
            Image = 94792767297608,
            Price = 5000000,
            Drop = {
                { "Plush Pepe (Poison Dart)", 25 },
                { "Plush Pepe (Hue Jester)", 22 },
                { "Plush Pepe (Amalgam)", 12 },
                { "Plush Pepe (Aqua Plush)", 12 },
                { "Plush Pepe (Emo Boi)", 10 },
                { "Plush Pepe (Emerald Plush)", 8 },
                { "Plush Pepe (Cozy Galaxy)", 6 },
                { "Plush Pepe (Midas Pepe)", 4 },
                { "Plush Pepe (Toading...)", 0.7 },
                { "Plush Pepe (Gucci Leap)", 0.2 },
                { "Plush Pepe (Hothead)", 0.1 }
            }
        },
        Glitch = {
            Image = 75712104636721,
            Price = 135000,
            Drop = {
                { "Artisan Brick (Concrete)", 30 },
                { "Heroic Helmet (Praetorian)", 22.6 },
                { "Precious Peach (Peach Black)", 20 },
                { "Loot Bag (Black Purrse)", 20 },
                { "Durov’s Cap (Shadow)", 5 },
                { "Heart Locket (Nightclub)", 2 },
                { "Plush Pepe (Emo Boi)", 0.3 },
                { "Heart Locket (Turtles)", 0.1 }
            }
        },
        URUS = {
            Image = 113680285408799,
            Price = 1666666,
            Drop = {
                { "Heart", 25 },
                { "Plush Pepe (Hue Jester)", 74.95 },
                { "Plush Pepe (X-Ray)", 0.05 }
            }
        },
        Cyber = {
            Image = 117934010640694,
            Price = 13444222,
            Drop = {
                { "Toy Bear (Blueprint)", 56 },
                { "Mood Pack (Bank Vault)", 39.34 },
                { "Happy Brownie (Toilet Bot)", 4 },
                { "Pool Float (Nessie)", 0.6 },
                { "Durov’s Figurine (Ilon)", 0.05 },
                { "Plush Pepe (Bavaria)", 0.01 }
            }
        },
        Festive = {
            Image = 96220025786883,
            Price = 50,
            SNOWFLAKES = true,
            Limited = true,
            Drop = {
                { "Ginger Cookie (Claus)", 45 },
                { "Sharp Tongue (Frostbite)", 25 },
                { "Bling Binky (Christmas)", 15 },
                { "Genie Lamp (Snow Globe)", 7 },
                { "Mighty Arm (Icebreaker)", 5 },
                { "Perfume Bottle (Blizzard)", 2.3 },
                { "Heart Locket (Winter)", 0.7 }
            }
        },
        Santa = {
            Image = 76467479616057,
            Price = 500,
            SNOWFLAKES = true,
            Limited = true,
            Drop = {
                { "Genie Lamp (Snow Globe)", 35 },
                { "Mighty Arm (Icebreaker)", 25 },
                { "Perfume Bottle (Blizzard)", 16 },
                { "Heart Locket (Winter)", 11 },
                { "Christmas Wreath", 7.5 },
                { "Loot Bag (Winter)", 5 },
                { "Plush Pepe (Frozen)", 0.5 }
            }
        },
        Reindeer = {
            Image = 127222842721638,
            Price = 2000,
            SNOWFLAKES = true,
            Limited = true,
            Drop = {
                { "Mini Oscar (Claus)", 70 },
                { "Neko Helmet (Frostbear)", 17 },
                { "Khabib\'s Papakha (Winter)", 8.66 },
                { "Loot Bag (Glacier)", 3.5 },
                { "Precious Peach (Xmas Lights)", 0.7 },
                { "Plush Pepe (Santa)", 0.21 },
                { "Plush Pepe (Christmas)", 0.02 }
            }
        },
        ["XMAS Night"] = {
            Image = 110966046941659,
            Price = 5000,
            SNOWFLAKES = true,
            Limited = true,
            Drop = {
                { "Christmas Tree", 99.7 },
                { "Telegram Pin (Christmas)", 0.25 },
                { "Gem Signet (XMAS Spinny Boi)", 0.05 }
            }
        },
        ["Porsche 911"] = {
            Image = 76723874472836,
            Price = 599999,
            Drop = {
                { "Durov’s Cap (Tron)", 95 },
                { "Heart Locket (Mecha Love)", 4.95 },
                { "Plush Pepe (Gucci Leap)", 0.05 }
            }
        },
        G63 = {
            Image = 97343275696585,
            Price = 177777,
            Drop = {
                { "Ion Gem (Prismatic)", 45 },
                { "Loot Bag (Crypto Byte)", 25 },
                { "Artisan Brick (Gold Block)", 15 },
                { "Heroic Helmet (Frozen Aegis)", 9 },
                { "Heart Locket (Shield of Sun)", 3 },
                { "Heart Locket (Delegram)", 2 },
                { "Plush Pepe (Amalgam)", 1 }
            }
        },
        ["M5 F90"] = {
            Image = 91905618241831,
            Price = 55555,
            Drop = {
                { "Astral Shard (Crystal Punk)", 45 },
                { "Mighty Arm (Body Builder)", 34 },
                { "Artisan Brick (Bomb Planted)", 11 },
                { "Cupid Charm (Pepe Love)", 5 },
                { "Precious Peach (Yin Yang)", 3.5 },
                { "Durov’s Cap (Neon)", 1.3 },
                { "Heart Locket (Neptune)", 0.2 }
            }
        },
        ["All In"] = {
            Image = 101374812394445,
            Price = 200,
            Paid = true,
            Drop = {
                { "Loot Bag (Pepe Bag)", 30 },
                { "Heart Locket (Shield of Sun)", 25 },
                { "Heart Locket (Saturn)", 20 },
                { "Heart Locket (Trapped Heart)", 15 },
                { "Plush Pepe (Aqua Plush)", 9.6 },
                { "Plush Pepe (Gucci Leap)", 0.4 }
            }
        },
        Dream = {
            Image = 137897894683277,
            Price = 250000,
            Drop = {
                { "Toy Bear (Dark Knight)", 43 },
                { "Mighty Arm (Gladiator)", 35 },
                { "Durov’s Cap (Sunrise)", 10.5 },
                { "Artisan Brick (USBrick)", 7 },
                { "Durov’s Cap (RGB Glitch)", 3 },
                { "Plush Pepe (Aqua Plush)", 1.5 }
            }
        },
        Manager = {
            Image = 99806181652051,
            Price = 835,
            Drop = {
                { "Snake Box", 30 },
                { "Clover Pin (Corrupted)", 25 },
                { "Jack in the box (Aliens)", 20 },
                { "Jolly Chimp (Retro Cartoon)", 9 },
                { "Easter Egg (Creeper)", 7 },
                { "Ginger Cookie (Headless)", 4 },
                { "Easter Egg (Boiled Pepe)", 2.5 },
                { "Hanging Star (This Is Fine)", 1.5 },
                { "Jester Hat (Pepe Hop)", 0.7 },
                { "Bonded Ring (Pixel Loot)", 0.3 }
            }
        },
        Premium = {
            Image = 103787870998417,
            Price = 50,
            Paid = true,
            Drop = {
                { "Jester Hat (Pepe Hop)", 25 },
                { "Ionic Dryer (Arc Reactor)", 20 },
                { "Signet Ring (Saturn Ring)", 18 },
                { "Astral Shard (Barbed)", 17 },
                { "Bonded Ring (Asteroid)", 14 },
                { "Nail Bracelet (Crypto Gem)", 4 },
                { "Magic Potion (Error Elixir)", 1.6 },
                { "Precious Peach (Crypto Orange)", 0.4 }
            }
        },
        ["Ninja Turtles"] = {
            Image = 81637665994885,
            Price = 10000000,
            Drop = {
                { "Mighty Arm (Pizza Pump)", 28 },
                { "Happy Brownie (Raphael)", 21 },
                { "Plush Pepe (Ninja Mike)", 13.85 },
                { "Plush Pepe (Donatello)", 13.63 },
                { "Plush Pepe (Raphael)", 12 },
                { "Plush Pepe (Leonardo)", 11.5 },
                { "Plush Pepe (Turtles)", 0.02 }
            }
        },
        Starter = {
            Image = 131935342493294,
            Price = 20,
            Paid = true,
            Drop = {
                { "Mad Pumpkin (Daredevil)", 25 },
                { "Kissed Frog (Ectofrog)", 21 },
                { "Toy Bear (Alter Ego)", 19 },
                { "Scared Cat (Cathulhu)", 15 },
                { "Genie Lamp (Star Dust)", 11 },
                { "Loot Bag (Road Trip)", 7 },
                { "Perfume Bottle (Rose Thorn)", 2 }
            }
        },
        Pepe10 = {
            Image = 91311078844219,
            Price = 100,
            Paid = true,
            Drop = {
                { "Heart", 85 },
                { "Plush Pepe (Aqua Plush)", 8 },
                { "Plush Pepe (Emo Boi)", 6 },
                { "Plush Pepe (Toading...)", 1 }
            }
        },
        Cats = {
            Image = 95375267833149,
            Price = 40000,
            Drop = {
                { "Gem Signet (Old Bronze)", 38 },
                { "Bonded Ring (Cat Bed)", 24.7 },
                { "Resistance Dog", 13 },
                { "Nail Bracelet (Cat Person)", 9.5 },
                { "Scared Cat (Obelisk)", 6 },
                { "Nail Bracelet (Moon Cat)", 4 },
                { "Genie Lamp (Cat Spirit)", 2.2 },
                { "Artisan Brick (Cash Roll)", 1.5 },
                { "Durov’s Cap (Fun Time)", 0.7 },
                { "Heart Locket (Fairy Dust)", 0.3 },
                { "Plush Pepe (Poison Dart)", 0.1 }
            }
        },
        ["Bubble Gum"] = {
            Image = 82224068961086,
            Price = 12000,
            Drop = {
                { "Fresh Socks (Billie Jean)", 38 },
                { "Low Rider (Neon Nitro)", 25.9 },
                { "Toy Bear (Fazbear)", 17 },
                { "Electric Skull (Half Alive)", 8 },
                { "Bonded Ring (Rainbow)", 5 },
                { "Astral Shard (Nectarite)", 3 },
                { "Loot Bag (City Life)", 1.5 },
                { "Gem Signet (8 Bit Diamond)", 1 },
                { "Heroic Helmet (Punk Skull)", 0.35 },
                { "Durov’s Cap (Sky High)", 0.25 }
            }
        },
        ["Frozen Heart"] = {
            Image = 87214395143906,
            Price = 4500,
            Drop = {
                { "Eternal Candle (Bubble Bath)", 45.8 },
                { "Cupid Charm (Crystal Clear)", 23 },
                { "Love Potion (Ice Queen)", 15 },
                { "Mad Pumpkin (Frostbite)", 10 },
                { "Kissed Frog (Ectofrog)", 4 },
                { "Astral Shard (Aquarium)", 1.6 },
                { "Precious Peach (Bubbling Blue)", 0.6 }
            }
        },
        Luxury = {
            Image = 117750720745301,
            Price = 119999,
            Drop = {
                { "Gem Signet (Death Star)", 32 },
                { "Electric Skull (Terminator)", 25 },
                { "Mini Oscar (Fiery-Hot)", 18 },
                { "Artisan Brick (Fight Club)", 8.7 },
                { "Heroic Helmet (Cyberpunk)", 7 },
                { "Nail Bracelet (Interstellar)", 5 },
                { "Precious Peach (Angelic)", 3 },
                { "Durov’s Cap (Falcon)", 1 },
                { "Heart Locket (Cirque)", 0.2 },
                { "Plush Pepe (Emerald Plush)", 0.1 }
            }
        },
        Burj = {
            Image = 93924885649377,
            Price = 37999,
            Drop = {
                { "Gem Signet (Amethyst)", 38.1 },
                { "Diamond Ring (Black Hole)", 25 },
                { "Astral Shard (Bogartite)", 15 },
                { "Genie Lamp (Lava Lamp)", 10 },
                { "Ion Gem (Prismatic)", 5 },
                { "Loot Bag (Conductor)", 4 },
                { "Mighty Arm (Crystal Fist)", 2 },
                { "Durov’s Cap (Honey Bee)", 0.6 },
                { "Plush Pepe (Hue Jester)", 0.3 }
            }
        },
        Palm = {
            Image = 72236024427706,
            Price = 13999,
            Drop = {
                { "Crystal Ball (Druid Circle)", 23.5 },
                { "Cupid Charm (Dryad Heart)", 18 },
                { "Love Potion (Banana)", 16 },
                { "Sakura Flower (Sunflower)", 13 },
                { "Kissed Frog (Lava Leap)", 11 },
                { "Gem Signet (Elven Shade)", 10 },
                { "Bonded Ring (Duckling)", 5.2 },
                { "Sakura Flower (Flowey)", 2.4 },
                { "Astral Shard (Eve\'s Apple)", 0.6 },
                { "Precious Peach (Rich Green)", 0.3 }
            }
        },
        Dark = {
            Image = 88276638893486,
            Price = 4999,
            Drop = {
                { "Evil Eye (8 Ball)", 37.75 },
                { "Hanging Star (Black Hole)", 20 },
                { "Bow Tie (Dark Lord)", 12 },
                { "Mad Pumpkin (Daredevil)", 9 },
                { "Record Player (Dark Noir)", 8 },
                { "Signet Ring (Obsidian)", 6 },
                { "Swiss Watch (Memory Flash)", 3.5 },
                { "Toy Bear (Ursa Major)", 1.75 },
                { "Gem Signet (Black Lotus)", 1 },
                { "Heroic Helmet (Black Thorn)", 0.6 },
                { "Loot Bag (Black Purrse)", 0.4 }
            }
        },
        Gold = {
            Image = 70908433442260,
            Price = 1999,
            Drop = {
                { "Lol Pop (Gold Star)", 40 },
                { "Bunny Muffin (Gold)", 33.5 },
                { "Love Candle (Golden Glow)", 15 },
                { "Ionic Dryer (Gold Rush)", 5 },
                { "Toy Bear (Golden Cub)", 2.5 },
                { "Low Rider (Gold Rush)", 2 },
                { "Swicc Watch (Day Trader)", 1.5 },
                { "Magic Potion (Gold Medal)", 0.35 },
                { "Artisan Brick (Gold Bar)", 0.15 }
            }
        },
        Daily = {
            Image = 114447727982920,
            Price = 0,
            Drop = {
                { "Desk Calendar", 80 },
                { "Flying Broom", 19 },
                { "Mighty Arm", 1 }
            }
        },
        Trash = {
            Image = 106599130323577,
            Price = 0,
            Drop = {
                { "Heart", 60 },
                { "Rose", 17 },
                { "Rocket", 7 },
                { "Flowers", 7 },
                { "Ring", 3 },
                { "Diamond", 3 },
                { "Lol Pop", 1.5 },
                { "Snoop Dogg", 1 },
                { "Jester Hat", 0.5 }
            }
        },
        Plodder = {
            Image = 106913820750482,
            Price = 444,
            Drop = {
                { "Ring", 36.3 },
                { "Snake Box", 15 },
                { "Xmax Stocking", 12 },
                { "Gigner Cookie", 8 },
                { "Pet Snake", 8 },
                { "Hex Pox", 7 },
                { "Sakura Flower", 6 },
                { "Hanging Star", 4 },
                { "Eternal Rose", 3 },
                { "Kissed Frog", 0.6 },
                { "Perfume Bottle", 0.1 }
            }
        },
        ["Office Clerk"] = {
            Image = 113128984263308,
            Price = 689,
            Drop = {
                { "Lol Pop", 43.4 },
                { "Hypno Lollipop", 12 },
                { "Star Notepad", 12 },
                { "Light Sword", 10 },
                { "Jolly Chimp", 8 },
                { "Valentine Box", 5 },
                { "Trapped Heart", 5 },
                { "Voodoo Doll", 4 },
                { "Scared Cat", 0.5 },
                { "Loot Bag", 0.09 },
                { "Mini Oscar", 0.01 }
            }
        },
        Director = {
            Image = 132224544380006,
            Price = 926,
            Drop = {
                { "Party Sparkler", 37.3 },
                { "Spy Agaric", 30 },
                { "Berry Box", 17 },
                { "Record Player", 7 },
                { "Cupid Charm", 5 },
                { "Toy Bear", 3 },
                { "Bonded Ring", 0.5 },
                { "Astral Shard", 0.2 }
            }
        },
        Oligarch = {
            Image = 72724304053316,
            Price = 1364,
            Drop = {
                { "Lush Bouquet", 35 },
                { "Jelly Bunny", 25 },
                { "Evil Eye", 21 },
                { "Mad Pumpkin", 9 },
                { "Ionic Dryer", 5 },
                { "Neko Helmet", 4 },
                { "Gem Signet", 0.85 },
                { "Heroic Helmet", 0.15 }
            }
        },
        Beggar = {
            Image = 88837808135921,
            Price = 220,
            Drop = {
                { "Diamond", 21 },
                { "Ring", 18.5 },
                { "Lol Pop", 16 },
                { "Lunar Snake", 15 },
                { "Tama Gadget", 12 },
                { "Holiday Drink", 10 },
                { "Witch Hat", 5 },
                { "Evil Eye", 2 },
                { "Love Potion", 0.5 }
            }
        }
    }
};
